// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-M0c-RJ-xCNdqVZoJyEtVzSbONffd96s',
    appId: '1:1098903323699:web:538234b0060315213f0f46',
    messagingSenderId: '1098903323699',
    projectId: 'lapor-book-2a1bf',
    authDomain: 'lapor-book-2a1bf.firebaseapp.com',
    storageBucket: 'lapor-book-2a1bf.appspot.com',
    measurementId: 'G-CRLQSFG5VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfv_pagmmouDKkW8fLt2i3b66T-T6pekQ',
    appId: '1:1098903323699:android:22b9f86095a3924f3f0f46',
    messagingSenderId: '1098903323699',
    projectId: 'lapor-book-2a1bf',
    storageBucket: 'lapor-book-2a1bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXptwJpZxNdo5uIvexLiFNNGvq-b8QH5Y',
    appId: '1:1098903323699:ios:f6d2ef488e71ab2a3f0f46',
    messagingSenderId: '1098903323699',
    projectId: 'lapor-book-2a1bf',
    storageBucket: 'lapor-book-2a1bf.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
